# see https://pyup.io/docs/configuration/ for all available options

# configure updates globally
# default: all
# allowed: all, insecure, False
update: insecure


# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
branch:

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule:

# search for requirement files
# default: True
# allowed: True, False
search: False

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
requirements:
  - requirements/base.txt:
      # update all dependencies and pin them
      update: False
      pin: False
  - requirements/dev.txt:
      # don't update dependencies, use global 'pin' default
      update: False
      pin: False
  - requirements/production.txt:
      # update insecure only, pin all
      update: False
      pin: False
  - requirements/constraints.txt:
      update: insecure
      pin: True

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs:

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
assignees:

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix:

# set a global prefix for PRs
# default: empty
pr_prefix:

# allow to close stale PRs
# default: True
close_prs: True
